# Generated by Django 5.2.7 on 2025-10-16 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Set_Point_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.CharField(default='Define your desired price below for 1 point in NZ dollar', editable=False, max_length=200)),
                ('point_value_nzd', models.DecimalField(decimal_places=4, default=0.01, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Set_Refferal_Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.CharField(default='Set the desired Points You want Users to win by using refferal code!', editable=False, max_length=200)),
                ('reward_points', models.PositiveBigIntegerField(default=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='staff/profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
