# Generated by Django 5.2.7 on 2025-10-18 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_info',
            old_name='user',
            new_name='staff_user',
        ),
    ]
