# Generated by Django 5.2.7 on 2025-10-24 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_user_staff_info_staff_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_info',
            name='staff_user',
            field=models.OneToOneField(limit_choices_to={'user_role': '3'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
