# Generated by Django 5.2.7 on 2025-12-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_info_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_point', models.PositiveIntegerField(help_text='Price per point in NZD cents')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Set_Point_Price',
        ),
        migrations.AlterField(
            model_name='set_refferal_points',
            name='reward_points',
            field=models.PositiveBigIntegerField(default=30),
        ),
    ]
