# Generated by Django 5.2.7 on 2026-01-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_pointspricing_delete_set_point_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsPerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_badge', models.PositiveIntegerField(default=20, help_text='Value per Badge in points')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pointspricing',
            name='price_per_point',
            field=models.PositiveIntegerField(default=0.01, help_text='Price per point in NZD cents'),
        ),
    ]
