# Generated by Django 5.2.7 on 2025-10-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_is_verified_customer_profile_referrals'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrals',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
