# Generated by Django 5.2.7 on 2025-10-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_code',
            name='otp',
            field=models.CharField(max_length=500),
        ),
    ]
