# Generated by Django 5.2.7 on 2025-10-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_earned_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referrals',
            old_name='refferal_code',
            new_name='referral_code',
        ),
        migrations.RenameField(
            model_name='referrals',
            old_name='refferal_code_user',
            new_name='referral_code_user',
        ),
    ]
