# Generated by Django 5.2.7 on 2025-10-20 18:26

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_points_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/user_default_img/user.png', null=True, upload_to=app.models.customer_upload_path),
        ),
        migrations.AlterField(
            model_name='earned_points',
            name='earned_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='points_spent',
            name='spent_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
