# Generated by Django 5.2.7 on 2025-10-21 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customer_interest_challenge_achiever_friendships_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_interest',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
