# Generated by Django 5.2.7 on 2025-10-24 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_interest_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='interests',
        ),
    ]
