# Generated by Django 5.2.7 on 2025-10-24 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_categories_post_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='interests',
            new_name='categories',
        ),
    ]
