# Generated by Django 5.2.7 on 2025-10-24 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_interests_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge_achiever',
            name='customer_taken',
            field=models.ForeignKey(limit_choices_to={'user_role': '1'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='earned_points',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'user_role': '1'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendships',
            name='request_getter',
            field=models.ForeignKey(limit_choices_to={'user_role': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_get_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendships',
            name='request_sender',
            field=models.ForeignKey(limit_choices_to={'user_role': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_send_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='points_spent',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'user_role': '1'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='raffles_entry',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_role': '1'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='referral_code_sender',
            field=models.ForeignKey(limit_choices_to={'user_role': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='invite_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='referral_code_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_role': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_getter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rewards_achiever',
            name='customer_taken',
            field=models.ForeignKey(limit_choices_to={'user_role': '1'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_interest',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_role': '1'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
