# Generated by Django 5.2.7 on 2025-10-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_challenge_achiever_customer_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_interest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/interests/'),
        ),
    ]
