# Generated by Django 5.2.7 on 2025-10-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_challenge_achiever_scanned_time_earned_badges_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge_achiever',
            name='scanned_time',
        ),
        migrations.RemoveField(
            model_name='earned_badges',
            name='time',
        ),
        migrations.RemoveField(
            model_name='earned_points',
            name='earned_time',
        ),
        migrations.RemoveField(
            model_name='points_spent',
            name='spent_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
        migrations.RemoveField(
            model_name='raffles_entry',
            name='joined_time',
        ),
        migrations.RemoveField(
            model_name='referrals',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='rewards_achiever',
            name='achieved_time',
        ),
        migrations.AlterField(
            model_name='challenge_achiever',
            name='scanned_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='earned_badges',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='earned_points',
            name='earned_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='points_spent',
            name='spent_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='raffles_entry',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rewards_achiever',
            name='achieved_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
