# Generated by Django 5.2.7 on 2025-10-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_challenge_achiever_scanned_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge_achiever',
            name='scanned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='earned_badges',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='earned_points',
            name='earned_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='points_spent',
            name='spent_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='raffles_entry',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
