# Generated by Django 5.2.7 on 2025-11-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_challenge_achiever_scanned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer_profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=12, null=True),
        ),
    ]
