# Generated by Django 5.2.7 on 2025-11-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_stamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_media_accounts',
            name='social_media',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('tiktok', 'TikTok'), ('youtube', 'Youtube')], max_length=30),
        ),
    ]
