# Generated by Django 5.2.7 on 2025-11-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_social_media_accounts_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge_achiever',
            name='points_issued',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
