# Generated by Django 5.2.7 on 2025-11-26 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_devicefcm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referrals',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='referrals',
            name='referral_code_user',
        ),
        migrations.AlterField(
            model_name='referrals',
            name='referral_code_sender',
            field=models.OneToOneField(limit_choices_to={'user_role': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='invite_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
