# Generated by Django 5.2.7 on 2025-12-04 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_customer_username'),
        ('venue', '0041_alter_food_menu_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVenueTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_tags', to='app.post')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venue_info')),
            ],
        ),
    ]
