# Generated by Django 5.2.7 on 2025-12-12 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_postvenuetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('code_user', models.ForeignKey(limit_choices_to={'user_role': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='referral_user', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.referrals')),
            ],
        ),
    ]
