# Generated by Django 5.2.7 on 2025-12-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_referralsusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralsusers',
            name='points_issued',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
