# Generated by Django 5.2.7 on 2025-12-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_customer_apple_sub_usercurrentappversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingandcomplains',
            name='adminAction',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reportingandcomplains',
            name='reason',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='termsandconditionsaccept',
            name='terms_version',
            field=models.CharField(max_length=50),
        ),
    ]
