# Generated by Django 5.2.7 on 2026-02-19 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_customer_is_google_or_apple_account'),
        ('venue', '0045_remove_challenges_specify_weekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_role',
            field=models.CharField(choices=[('1', 'customer'), ('2', 'venue'), ('3', 'staff'), ('4', 'organiser')], default='1', max_length=15),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=3000)),
                ('image', models.ImageField(upload_to='uploads/events')),
                ('location', models.CharField(max_length=500)),
                ('event_start_date', models.DateTimeField()),
                ('event_close_date', models.DateTimeField()),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('organziser_notice', models.CharField(max_length=2000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('upcoming', 'Upcoming'), ('completed', 'Completed')], default='draft')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conditions', models.CharField(blank=True, max_length=1000, null=True)),
                ('physical_reward', models.CharField(blank=True, max_length=1000, null=True)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue.badges')),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'user_role__in': ['3', '4']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.qr_info')),
            ],
        ),
        migrations.CreateModel(
            name='EventPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.events')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('attended', models.BooleanField(default=False)),
                ('user', models.ForeignKey(limit_choices_to={'user_role': '1'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.events')),
            ],
        ),
        migrations.CreateModel(
            name='VenuesParticipatingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scans_to_achieve_next_tier', models.PositiveIntegerField(blank=True, help_text='Number of scans to achieve next tier in the selected venue', null=True)),
                ('availabile_till', models.DateTimeField(auto_now_add=True)),
                ('scan_unique_challenges', models.BooleanField(default=False, help_text="If you have more than 1 number of scans to achieve next tier challenges then check this if you want users to scan unique challenges to achieve next tire else left it uncheck if you don't want keep scans unique")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.events')),
                ('venues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venue_info')),
            ],
        ),
    ]
