# Generated by Django 5.2.7 on 2026-02-19 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_customer_user_role_events_eventposts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='organziser_notice',
            new_name='organiser_notice',
        ),
    ]
