# Generated by Django 5.2.7 on 2026-02-21 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_rename_organziser_notice_events_organiser_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventposts',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.events'),
        ),
        migrations.AlterField(
            model_name='eventposts',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.post'),
        ),
    ]
