# Generated by Django 5.2.7 on 2026-02-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_eventposts_event_alter_eventposts_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='app.customer_interest'),
        ),
    ]
