# Generated by Django 5.2.7 on 2026-02-26 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_post_categories'),
        ('venue', '0045_remove_challenges_specify_weekday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuesparticipatingevents',
            name='availabile_till',
        ),
        migrations.RemoveField(
            model_name='venuesparticipatingevents',
            name='scan_unique_challenges',
        ),
        migrations.AlterField(
            model_name='eventposts',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.events'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventposts',
            name='posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.badges'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='app.customer_interest'),
        ),
    ]
