# Generated by Django 5.2.7 on 2026-02-27 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_venuesparticipatingevents_availabile_till_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuesparticipatingevents',
            name='venues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
