# Generated by Django 5.2.7 on 2026-03-05 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_venuesparticipatingevents_venues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendees',
            name='joined_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='EventBadgesEarned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_issued', models.PositiveIntegerField(blank=True, null=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.events')),
                ('user', models.ForeignKey(limit_choices_to={'user_role': '1'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
