# Generated by Django 5.2.7 on 2026-03-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_eventattendees_joined_at_eventbadgesearned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
