# Generated by Django 5.2.7 on 2026-03-12 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_events_latitude_alter_events_longitude'),
        ('venue', '0045_remove_challenges_specify_weekday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbadgesearned',
            name='badge_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venue.badgeslevel'),
            preserve_default=False,
        ),
    ]
