# Generated by Django 5.2.7 on 2026-03-12 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_eventbadgesearned_badge_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbadgesearned',
            name='badge_level',
        ),
    ]
