# Generated by Django 5.2.7 on 2026-03-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_eventbadgesearned_badge_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='qr_code',
        ),
        migrations.DeleteModel(
            name='EventBadgesEarned',
        ),
    ]
