# Generated by Django 5.2.7 on 2026-03-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_events_qr_code_delete_eventbadgesearned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendees',
            name='attended',
        ),
    ]
