# Generated by Django 5.2.7 on 2026-03-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_remove_eventattendees_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuesparticipatingevents',
            name='availabile_till',
            field=models.DateTimeField(blank=True, help_text='The date and time until which users have to scan on this venue', null=True),
        ),
    ]
