# Generated by Django 5.2.7 on 2026-05-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_remove_eventattendees_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='total_scans_required',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='venuesparticipatingevents',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='The date and time from which users can start scanning on this venue', null=True),
        ),
        migrations.AddField(
            model_name='venuesparticipatingevents',
            name='available_till',
            field=models.DateTimeField(blank=True, help_text='The date and time until which users have to scan on this venue', null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='organiser_notice',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.ManyToManyField(related_name='events_categories', to='app.eventcategory'),
        ),
    ]
