# Generated by Django 5.2.7 on 2026-03-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_venuesparticipatingevents_availabile_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuesparticipatingevents',
            name='availabile_till',
            field=models.DateTimeField(help_text='The date and time until which users have to scan on this venue'),
        ),
    ]
