# Generated by Django 5.2.7 on 2026-06-08 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_eventcategory_events_total_scans_required_and_more'),
        ('venue', '0046_menu_items_menu_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venue.badges'),
        ),
        migrations.AlterField(
            model_name='venuesparticipatingevents',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='The date and time from which users can start scanning on this venue', null=True),
        ),
        migrations.AlterField(
            model_name='venuesparticipatingevents',
            name='available_till',
            field=models.DateTimeField(blank=True, help_text='The date and time until which users have to scan on this venue', null=True),
        ),
    ]
