# Generated by Django 5.2.7 on 2026-06-20 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_events_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='buy_now_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_role__in': ['2', '3', '4']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
