# Generated by Django 5.2.7 on 2026-03-17 22:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_venuesparticipatingevents_availabile_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuesparticipatingevents',
            name='availabile_till',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time until which users have to scan on this venue'),
        ),
    ]
