# Generated by Django 5.2.7 on 2026-06-22 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_events_buy_now_link_alter_events_created_by'),
        ('venue', '0046_menu_items_menu_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='raffle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venue.raffles'),
        ),
    ]
