# Generated by Django 5.2.7 on 2026-03-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_venuesparticipatingevents_availabile_till'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venuesparticipatingevents',
            old_name='availabile_till',
            new_name='available_till',
        ),
    ]
