# Generated by Django 5.2.7 on 2026-04-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_rename_availabile_till_venuesparticipatingevents_available_till'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='events',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
