# Generated by Django 5.2.7 on 2026-04-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_eventcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.ManyToManyField(related_name='events_categories', to='app.eventcategory'),
        ),
    ]
