# Generated by Django 5.2.7 on 2026-04-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_events_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='organiser_notice',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
