# Generated by Django 5.2.7 on 2025-10-18 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_badges_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badges',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.badge_category'),
        ),
    ]
