# Generated by Django 5.2.7 on 2025-10-20 19:30

import django.db.models.deletion
import venue.models.menu
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_alter_badges_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to=venue.models.menu.venue_file_upload_path),
        ),
        migrations.AddField(
            model_name='venue_info',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue_opening_hours',
            name='friday',
            field=models.CharField(help_text='if closed so write closed else mention timings', max_length=50),
        ),
        migrations.AlterField(
            model_name='venue_opening_hours',
            name='monday',
            field=models.CharField(help_text='if closed so write closed else mention timings', max_length=50),
        ),
        migrations.AlterField(
            model_name='venue_opening_hours',
            name='saturday',
            field=models.CharField(help_text='if closed so write closed else mention timings', max_length=50),
        ),
        migrations.AlterField(
            model_name='venue_opening_hours',
            name='sunday',
            field=models.CharField(help_text='if closed so write closed else mention timings', max_length=50),
        ),
        migrations.AlterField(
            model_name='venue_opening_hours',
            name='thursday',
            field=models.CharField(help_text='if closed so write closed else mention timings', max_length=50),
        ),
        migrations.AlterField(
            model_name='venue_opening_hours',
            name='tuesday',
            field=models.CharField(help_text='if closed so write closed else mention timings', max_length=50),
        ),
        migrations.AlterField(
            model_name='venue_opening_hours',
            name='wednesday',
            field=models.CharField(help_text='if closed so write closed else mention timings', max_length=50),
        ),
    ]
