# Generated by Django 5.2.7 on 2025-10-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_menu_items_item_image_venue_info_venue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badges',
            name='num_of_task_to_achieve_badge',
        ),
        migrations.AddField(
            model_name='badge_category',
            name='num_of_task_to_achieve_badge',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
