# Generated by Django 5.2.7 on 2025-10-20 22:24

import django.db.models.deletion
import uuid
import venue.models.qr_info_model
import venue.models.rewards
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_remove_badges_num_of_task_to_achieve_badge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QR_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('winning_points', models.PositiveIntegerField(default=20)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to=venue.models.qr_info_model.challenge_upload_path)),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=350, null=True)),
                ('cool_down_hours', models.PositiveIntegerField()),
                ('daily_cap', models.PositiveIntegerField(help_text='Define how many times a Challenge can be attempted in a day?')),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_approved', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='pending', max_length=50)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.badges')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.qr_info')),
            ],
        ),
        migrations.CreateModel(
            name='Raffles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('rewards', models.CharField(blank=True, max_length=250, null=True)),
                ('points_to_join', models.PositiveIntegerField()),
                ('rewarded_points', models.PositiveIntegerField(blank=True, help_text='points will be rewarded to winner (optional)', null=True)),
                ('start_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_ended', models.BooleanField(default=False)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=venue.models.rewards.rewards_file_upload_path)),
                ('title', models.CharField(max_length=150)),
                ('condition', models.CharField(blank=True, max_length=250, null=True)),
                ('stock', models.PositiveIntegerField(default=50)),
                ('required_points_for_reward', models.PositiveIntegerField(default=50)),
                ('is_approved', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='pending', max_length=50)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_ended', models.BooleanField(default=False)),
                ('rewards_for_badge_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.badges')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
