# Generated by Django 5.2.7 on 2025-10-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0006_qr_info_challenges_raffles_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffles',
            name='num_of_winners',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
