# Generated by Django 5.2.7 on 2025-10-21 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0007_raffles_num_of_winners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='rewards_for_badge_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venue.badge_category'),
        ),
    ]
