# Generated by Django 5.2.7 on 2025-10-24 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0009_alter_venue_info_venue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='venue',
            field=models.ForeignKey(limit_choices_to={'user_role': '2'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food_menu_category',
            name='venue',
            field=models.ForeignKey(limit_choices_to={'user_role': '2'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='raffles',
            name='venue',
            field=models.ForeignKey(limit_choices_to={'user_role': '2'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='venue',
            field=models.ForeignKey(limit_choices_to={'user_role': '2'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venue_opening_hours',
            name='venue',
            field=models.OneToOneField(limit_choices_to={'user_role': '2'}, on_delete=django.db.models.deletion.CASCADE, related_name='venue', to=settings.AUTH_USER_MODEL),
        ),
    ]
