# Generated by Django 5.2.7 on 2025-10-24 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0010_alter_challenges_venue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Venue_Badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.badges')),
                ('venue', models.ForeignKey(limit_choices_to={'user_role': '2'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='challenges',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venue_badges'),
        ),
    ]
