# Generated by Django 5.2.7 on 2025-10-28 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0011_challenges_is_ended_venue_badges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenges',
            name='created_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='challenges',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue_info',
            name='venue_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
