# Generated by Django 5.2.7 on 2025-10-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0012_challenges_close_time_challenges_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='created_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
