# Generated by Django 5.2.7 on 2025-10-30 22:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0013_alter_challenges_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenges',
            old_name='close_time',
            new_name='daily_close_time',
        ),
        migrations.RenameField(
            model_name='challenges',
            old_name='open_time',
            new_name='daily_open_time',
        ),
        migrations.RenameField(
            model_name='challenges',
            old_name='starting_date',
            new_name='starting_at',
        ),
        migrations.RemoveField(
            model_name='challenges',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='challenges',
            name='ending_date',
        ),
        migrations.RemoveField(
            model_name='raffles',
            name='start_date',
        ),
        migrations.AddField(
            model_name='challenges',
            name='ending_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raffles',
            name='ended_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raffles',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenges',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='raffles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
