# Generated by Django 5.2.7 on 2025-10-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0014_rename_close_time_challenges_daily_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='daily_close_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='daily_open_time',
            field=models.TimeField(),
        ),
    ]
