# Generated by Django 5.2.7 on 2025-10-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0015_alter_challenges_daily_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffles',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
