# Generated by Django 5.2.7 on 2025-10-31 21:43

import venue.models.raffles
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0016_alter_raffles_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=venue.models.raffles.raffle_file_upload_path),
        ),
    ]
