# Generated by Django 5.2.7 on 2025-10-31 21:47

import venue.models.raffles
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0018_alter_raffles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffles',
            name='image',
            field=models.ImageField(default='media/raffle_default/raffle.png', upload_to=venue.models.raffles.raffle_file_upload_path),
        ),
    ]
