# Generated by Django 5.2.7 on 2025-11-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0020_alter_raffles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_info',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
