# Generated by Django 5.2.7 on 2025-11-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0021_alter_qr_info_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='ending_at',
            field=models.DateTimeField(),
        ),
    ]
