# Generated by Django 5.2.7 on 2025-11-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0022_alter_challenges_ending_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='starting_at',
            field=models.DateTimeField(),
        ),
    ]
