# Generated by Django 5.2.7 on 2025-11-03 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0023_alter_challenges_starting_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue_info',
            name='venue',
            field=models.ForeignKey(limit_choices_to={'user_role': '2'}, on_delete=django.db.models.deletion.CASCADE, related_name='venue_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
