# Generated by Django 5.2.7 on 2025-11-03 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0024_alter_venue_info_venue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue_info',
            name='venue',
            field=models.OneToOneField(limit_choices_to={'user_role': '2'}, on_delete=django.db.models.deletion.CASCADE, related_name='venue_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
