# Generated by Django 5.2.7 on 2025-11-03 21:27

import venue.models.challenges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0025_alter_venue_info_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='image',
            field=models.ImageField(default='media/challenge_default/scan.jpg', upload_to=venue.models.challenges.challenge_file_upload_path),
        ),
    ]
