# Generated by Django 5.2.7 on 2025-11-11 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0026_challenges_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='avialble_to_badge_holder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venue.badge_category'),
            preserve_default=False,
        ),
    ]
