# Generated by Django 5.2.7 on 2025-11-11 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0027_challenges_avialble_to_badge_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='avialble_to_badge_holder',
        ),
    ]
