# Generated by Django 5.2.7 on 2025-11-12 00:04

import venue.models.badges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0028_remove_challenges_avialble_to_badge_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badges',
            name='image',
            field=venue.models.badges.SVGAndImageField(upload_to='media/badges/', validators=[venue.models.badges.SVGAndImageValidator()]),
        ),
    ]
