# Generated by Django 5.2.7 on 2025-11-12 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0029_alter_badges_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr_info',
            name='winning_points',
        ),
    ]
