# Generated by Django 5.2.7 on 2025-11-13 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0030_remove_qr_info_winning_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badges',
            name='category',
        ),
        migrations.RemoveField(
            model_name='badges',
            name='image',
        ),
    ]
