# Generated by Django 5.2.7 on 2025-11-13 19:36

import django.db.models.deletion
import venue.models.badges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0031_remove_badges_category_remove_badges_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badges',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='BadgesLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', venue.models.badges.SVGAndImageField(upload_to='media/badges/', validators=[venue.models.badges.SVGAndImageValidator()])),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.badges')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.badge_category')),
            ],
        ),
    ]
