# Generated by Django 5.2.7 on 2025-11-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0032_alter_badges_name_badgeslevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badges',
            name='points_per_task',
        ),
        migrations.AddField(
            model_name='badgeslevel',
            name='points_per_task',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
