# Generated by Django 5.2.7 on 2025-11-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0033_remove_badges_points_per_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewards',
            name='rewards_for_badge_holder',
        ),
        migrations.AddField(
            model_name='rewards',
            name='rewards_for_badge_holder',
            field=models.ManyToManyField(to='venue.badges'),
        ),
    ]
