# Generated by Django 5.2.7 on 2025-11-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0034_remove_rewards_rewards_for_badge_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue_info',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='pending', max_length=20, null=True),
        ),
    ]
