# Generated by Django 5.2.7 on 2025-11-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0035_alter_venue_info_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffles',
            name='is_approved',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='pending', max_length=50),
        ),
    ]
