# Generated by Django 5.2.7 on 2025-11-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0036_raffles_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='is_approved',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='approved', max_length=50),
        ),
        migrations.AlterField(
            model_name='raffles',
            name='is_approved',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='approved', max_length=50),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='is_approved',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='approved', max_length=50),
        ),
        migrations.AlterField(
            model_name='venue_info',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='venue_info',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='venue_info',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='approved', max_length=20, null=True),
        ),
    ]
