# Generated by Django 5.2.7 on 2025-11-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0037_alter_challenges_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenges',
            old_name='cool_down_hours',
            new_name='cool_down_minutes',
        ),
        migrations.RemoveField(
            model_name='challenges',
            name='daily_close_time',
        ),
        migrations.RemoveField(
            model_name='challenges',
            name='daily_open_time',
        ),
    ]
