# Generated by Django 5.2.7 on 2025-11-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0038_rename_cool_down_hours_challenges_cool_down_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue_info',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
