# Generated by Django 5.2.7 on 2025-11-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0039_alter_venue_info_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items',
            name='item_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
