# Generated by Django 5.2.7 on 2025-11-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0040_alter_menu_items_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_menu_category',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='item_description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='item_name',
            field=models.CharField(max_length=150),
        ),
    ]
