# Generated by Django 5.2.7 on 2025-12-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0041_alter_food_menu_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='raffles',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='condition',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
