# Generated by Django 5.2.7 on 2026-02-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0043_challenges_close_time_challenges_open_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='cool_down_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
