# Generated by Django 5.2.7 on 2026-02-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0044_alter_challenges_cool_down_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='specify_weekday',
        ),
        migrations.AddField(
            model_name='challenges',
            name='specify_weekdays',
            field=models.JSONField(blank=True, default=list, help_text='List of weekdays (0=Monday, 6=Sunday)'),
        ),
    ]
