# Generated by Django 5.2.7 on 2026-04-29 23:39

import django.db.models.deletion
import venue.models.menu
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0045_remove_challenges_specify_weekday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='menu_file',
            field=models.FileField(blank=True, null=True, upload_to=venue.models.menu.venue_file_upload_path, validators=[venue.models.menu.validate_menu_file, venue.models.menu.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='item_description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='item_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='menu_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='venue.food_menu_category'),
        ),
    ]
