# Generated by Django 5.2.7 on 2026-07-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0046_menu_items_menu_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue_info',
            name='add_to_popular',
            field=models.BooleanField(default=False),
        ),
    ]
