"""
Django settings for oasis project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url
import ssl
import certifi
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



#For production
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")  # leave empty in production
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")  # leave empty in production
AWS_S3_REGION_NAME = "us-east-1"


import boto3


#For Production
ssm = boto3.client('ssm', region_name=AWS_S3_REGION_NAME)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


secret_key = ssm.get_parameter(
    Name='/myOasis/DJANGO_SECRET_KEY',
    WithDecryption=True
)['Parameter']['Value']

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secret_key

# SECURITY WARNING: don't run with debug turned on in production!

debug_value = ssm.get_parameter(
    Name='/myOasis/DEBUG',
    WithDecryption=False
)['Parameter']['Value']

DEBUG = debug_value.lower() == 'true'


hosts = ssm.get_parameter(
    Name='/myOasis/ALLOWED_HOSTS',
    WithDecryption=False
)['Parameter']['Value']

ALLOWED_HOSTS = hosts.split(",")


# Optional: trust your Railway domain for CSRF
CSRF_TRUSTED_ORIGINS = [
    f"https://{host}" for host in ALLOWED_HOSTS if host not in ["localhost", "127.0.0.1"]
]


    

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.apps.AppConfig',
    'staff',
    'venue.apps.VenueConfig',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'storages',
    'django_crontab',
]



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}

CORS_ALLOW_ALL_ORIGINS = False 


cross_origins = ssm.get_parameter(
    Name='/myOasis/CORS_ALLOWED_ORIGINS',
    WithDecryption=False
)['Parameter']['Value']

CORS_ALLOWED_ORIGINS = cross_origins.split(",")


CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_CREDENTIALS = True

google_client_id_param = ssm.get_parameter(
    Name="/myOasis/GOOGLE_WEB_CLIENT_ID",
    WithDecryption=True
)['Parameter']['Value']
GOOGLE_WEB_CLIENT_ID = google_client_id_param


from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'oasis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oasis.wsgi.application'

QR_BASE_URL = "https://api.venue-myoasis.co.nz/"  # Replace with your actual base URL for QR codes

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

db_url = ssm.get_parameter(
    Name='/myOasis/DATABASE_URL',
    WithDecryption=True
)['Parameter']['Value']
os.environ['DATABASE_URL'] = db_url


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Get DATABASE_URL from environment (Railway sets this automatically)
DATABASE_URL = config('DATABASE_URL', default=None)

# If DATABASE_URL exists, use PostgreSQL (normal Django backend)
if DATABASE_URL:
    DATABASES['default'] = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=True,
    )
    # Force the engine to standard PostgreSQL backend
    DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'


AUTH_USER_MODEL = 'app.Customer'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

STORAGES = {
    "default": {
        "BACKEND": "oasis.storage_backends.MediaStorage",
        # This is your DEFAULT_FILE_STORAGE (Media Files)
    },
    "staticfiles": {
        "BACKEND": "oasis.storage_backends.StaticStorage",
        # This is your STATICFILES_STORAGE (Static Files for collectstatic)
    }
}


apple_private_key_param = ssm.get_parameter(
    Name="/myOasis/prod/apple/signin/private_key",
    WithDecryption=True
)['Parameter']['Value']
APPLE_PRIVATE_KEY = apple_private_key_param

apple_client_id_param = ssm.get_parameter(
    Name="/myOasis/APPLE_CLIENT_ID",
    WithDecryption=True
)['Parameter']['Value']
APPLE_CLIENT_ID=apple_client_id_param

apple_team_id_param = ssm.get_parameter(
    Name="/myOasis/APPLE_TEAM_ID",
    WithDecryption=True
)['Parameter']['Value']
APPLE_TEAM_ID=apple_team_id_param 


apple_key_id_param = ssm.get_parameter(
    Name="/myOasis/APPLE_KEY_ID",
    WithDecryption=True
)['Parameter']['Value']
APPLE_KEY_ID=apple_key_id_param




facebook_app_id_param = ssm.get_parameter(
    Name="/myOasis/FACEBOOK_APP_ID",
    WithDecryption=True
)['Parameter']['Value']
FACEBOOK_APP_ID = facebook_app_id_param


facebook_app_secret_param = ssm.get_parameter(
    Name="/myOasis/FACEBOOK_APP_SECRET",
    WithDecryption=True
)['Parameter']['Value']
FACEBOOK_APP_SECRET = facebook_app_secret_param




# IMPORTANT: Remove or comment out STATICFILES_STORAGE and DEFAULT_FILE_STORAGE
# to avoid a conflict.


from firebase_admin import credentials, initialize_app

param = ssm.get_parameter(Name="/myOasis/firebase/key", WithDecryption=True)
key_json = param["Parameter"]["Value"]

# Write to temporary file
with open("/tmp/firebase_key.json", "w") as f:
    f.write(key_json)

cred = credentials.Certificate("/tmp/firebase_key.json")
initialize_app(cred)



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Pacific/Auckland'

USE_I18N = True

USE_TZ = True               


EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"


sendgrid_api = ssm.get_parameter(
    Name='/myOasis/SENDGRID_API_KEY',
    WithDecryption=True
)['Parameter']['Value']
SENDGRID_API_KEY = sendgrid_api

email_host = ssm.get_parameter(
    Name='/myOasis/EMAIL_HOST_USER',
    WithDecryption=False
)['Parameter']['Value']
DEFAULT_FROM_EMAIL=email_host



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



# Optional – Disable sandbox mode (real emails will be sent)
SENDGRID_SANDBOX_MODE_IN_DEBUG = False
# Optional – Do not store API key in database
SENDGRID_ECHO_TO_STDOUT = False






# Public files (STATIC)


bucket = ssm.get_parameter(
    Name='/myOasis/AWS_STORAGE_BUCKET_NAME',
    WithDecryption=True
)['Parameter']['Value']
AWS_STORAGE_BUCKET_NAME = bucket
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_DEFAULT_ACL = None
AWS_S3_FILE_OVERWRITE = False
AWS_QUERYSTRING_AUTH = False  # ✅ public URLs without ?signature= params

AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",
}
AWS_LOCATION = ""
# ✅ Custom domain (public endpoint)
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"

# ✅ Optional: specify the subfolders for static and media (recommended)
STATICFILES_LOCATION = "static"
MEDIAFILES_LOCATION = "media"

# ✅ Use custom storage classes (best practice)
STATICFILES_STORAGE = "oasis.storage_backends.StaticStorage"
DEFAULT_FILE_STORAGE = "oasis.storage_backends.MediaStorage"

# ✅ URLs
STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{STATICFILES_LOCATION}/"
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{MEDIAFILES_LOCATION}/"

# ✅ Local fallback
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "media"


CRONJOBS = [
    ('0 18 * * 1', 'app.cron.send_daily_notification')
]





